// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnj5pf7VX-Ern0JsR6M2eTIHsO-rC6joA',
    appId: '1:608936793162:web:d068d0d2dde2d9a9ebc2b3',
    messagingSenderId: '608936793162',
    projectId: 'raktdaata-b759b',
    authDomain: 'raktdaata-b759b.firebaseapp.com',
    storageBucket: 'raktdaata-b759b.appspot.com',
    measurementId: 'G-B80C3V70VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC8XgbqEFsKXEbLCaeAnq112PSPZgUjmM',
    appId: '1:608936793162:android:36eeedda0e30698cebc2b3',
    messagingSenderId: '608936793162',
    projectId: 'raktdaata-b759b',
    storageBucket: 'raktdaata-b759b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjd588F5z9mbdMUG5ce92VsmmdiakpFb8',
    appId: '1:608936793162:ios:87a7f44db6395bffebc2b3',
    messagingSenderId: '608936793162',
    projectId: 'raktdaata-b759b',
    storageBucket: 'raktdaata-b759b.appspot.com',
    iosClientId: '608936793162-suf1rgvosf5su3b6nk5eaoleubfkjj3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.raktdataApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjd588F5z9mbdMUG5ce92VsmmdiakpFb8',
    appId: '1:608936793162:ios:5b4399aeb32e2721ebc2b3',
    messagingSenderId: '608936793162',
    projectId: 'raktdaata-b759b',
    storageBucket: 'raktdaata-b759b.appspot.com',
    iosClientId: '608936793162-homlmqfd9lk5afhmnom1pb571m88g7jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.raktdataApp.RunnerTests',
  );
}
